FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.run
ENV FLASK_ENV=production
ENV JWT_SECRET_KEY=super-secret-change-me

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app.run:app"]
